server:
  port: 8081
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
spring:
  application:
    name: "Proposal-CrediYa"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  config:
    activate:
      on-profile: dev
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

routes:
  base-path: /api/v1
  paths:
    proposals: "/solicitud"
    states: "/estado"
    proposalTypes: "/tipo-prestamo"

clients:
  users: http://localhost:8080/api/v1/usuarios
  auth: http://localhost:8080/api/v1/autenticacion

adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "postgres"
    schema: "public"
    username: "postgres"
    password: "chupaelperro"
